### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by winksaville** [schteve/nucleo-f446re#4]
I'd like to suggest enabling [Discussions here on GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) for this repo or maybe use Discord or …

**Comment by schteve** [comment]
Sure, might as well try out discussions. Should be up now.

**Comment by winksaville** [comment]
Txs
